"""add profiles table, department/city on orders

Revision ID: 324bac806a4a
Revises: 65b61cee47c3
Create Date: 2026-07-07 00:47:55.102291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324bac806a4a'
down_revision: Union[str, None] = '65b61cee47c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('orders', sa.Column('department', sa.String(length=60), server_default='', nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(length=60), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'department')
    op.drop_table('profiles')
    # ### end Alembic commands ###
