"""add order_messages table

Revision ID: 65b61cee47c3
Revises: a998aa818e8d
Create Date: 2026-07-07 00:07:43.166008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b61cee47c3'
down_revision: Union[str, None] = 'a998aa818e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_messages_order_id'), 'order_messages', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_messages_order_id'), table_name='order_messages')
    op.drop_table('order_messages')
    # ### end Alembic commands ###
