"""add customer_phone to orders

Revision ID: a998aa818e8d
Revises: 81f743424747
Create Date: 2026-07-06 23:32:14.102187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a998aa818e8d'
down_revision: Union[str, None] = '81f743424747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    # ### end Alembic commands ###
